on: push
name: Deploy
jobs:
  Review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
            node-version: '15'
      - run: npm install
      - run: npm run review
  Build:
    runs-on: ubuntu-latest
    needs: Review
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          path: | 
            ~/.stack
            ./.stack-work
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.3'
          enable-stack: 'true'
          stack-version: latest
      - run: stack build
      - run: stack exec site build
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./_site --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
